Начало работы с Python
---------------------------

Новичок в Python? Давай правильно настроим вашу среду Python:
  

.. toctree::
   :maxdepth: 2

   starting/which-python

- Properly Install Python on your system:

 .. toctree::
    :maxdepth: 1

    starting/installation
    starting/install3/osx
    starting/install3/win
    starting/install3/linux
    starting/install/osx
    starting/install/win
    starting/install/linux


- Using Virtualenvs with Pipenv:

 .. toctree::
    :maxdepth: 2

    dev/virtualenvs

Среды разработки на Python
-------------------------------

This part of the guide focuses on the Python development environment,
and the best-practice tools that are available for writing Python code.

.. toctree::
   :maxdepth: 2

   dev/env
   dev/virtualenvs
   dev/pip-virtualenv



Написание отличного кода на Python
-------------------------

This part of the guide focuses on the best-practices for writing Python code.

.. toctree::
   :maxdepth: 2

   writing/structure
   writing/style
   writing/reading
   writing/documentation
   writing/tests
   writing/logging
   writing/gotchas
   writing/license


Руководство по сценариям для приложений на Python
--------------------------------------

This part of the guide focuses on tool and module advice based on
different scenarios.

.. toctree::
   :maxdepth: 2

   scenarios/client
   scenarios/web
   scenarios/scrape
   scenarios/cli
   scenarios/gui
   scenarios/db
   scenarios/network
   scenarios/admin
   scenarios/ci
   scenarios/speed
   scenarios/scientific
   scenarios/imaging
   scenarios/serialization
   scenarios/xml
   scenarios/json
   scenarios/crypto
   scenarios/ml
   scenarios/clibs


Доставка отличного кода на Python
--------------------------

This part of the guide focuses on sharing and deploying your Python code.

.. toctree::
   :maxdepth: 2

   shipping/publishing
   shipping/packaging
   shipping/freezing


Дополнительные примечания
----------------

This part of the guide, which is mostly prose, begins with some
background information about Python, and then focuses on next steps.

.. toctree::
   :maxdepth: 2

   intro/duction
   intro/community
   intro/learning
   intro/documentation
   intro/news

.. note::
   Примечания, определенные во всех диатонических и хроматических музыкальных 
   гаммах, были намеренно исключены из этого списка дополнительных примечаний. 
   Кроме этого примечания.
   

--------------------------------------

Примечания к вкладу и юридическая информация (для тех, кто заинтересован).

.. toctree::
   :maxdepth: 2

   notes/contribute
   notes/license
   notes/styleguide
